# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08c6e4d5e163299ecd6517d2f4c04ad76f618cbac25925ba1cd244d8f9cef061222fb76cced455b658edd650e9367f7e0bb858c11aed2b58a3f6a082e8451f91

test:
  secret_key_base: de4f225732615d2fc81fd1e954c1b361d16ec307ee6bfc31724766214e97a4e7e0f2cebb127dd3ea780168b3244912b3a1b93c3da3c1921ab15d4c42daaf6523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
